---
title: "日本社会心理学会　第5回春の方法論セミナー"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# RとRstudio入門

## 想定する対象者

+ Rを使ってみたいとおもっているけど，まだ本格導入をしていない方
+ Rを使いはじめてはみたけれど，Rならではの利点を感じていない方
+ Rを使わなければならないけれど，今までのやり方をRでどう表現するか自信のない方

## 参加者の皆さんへ

### 準備していただきたいもの

R/RStudioはフリーソフトウェアです。

+ Rの最新バージョンをインストールしておいてください。
	+ [The Comprehensive R Archive Network](https://cran.r-project.org)より自分の環境(Window/Mac/Linux)にあったRインストーラをダウンロードし，実行します。
	+ Rの最新バージョンは3.4.4です。(2018/3/20現在)
	+ Windowsマシンの場合
		+ インストールの際は，R for Windowsのリンクより，baseを選択し,Download R 3.4.3 for Windowsを選択して下さい。
		+ ユーザ名に2バイト文字が含まれていると不具合を起こすことがあります。その場合はお手数ですが，半角英数文字だけのアカウントを作成してください。
		+ インストールに際しては管理者権限を持っているアカウントで実行してください。
+ RStudioの最新バージョンをインストールしておいてください。
	+ [RStudioのサイト](https://www.rstudio.com)より，Download RStudio Desktopを選択，インストーラを入手して実行してください。
	+ Free Editionで構いません。
	+ RStudioの最新バージョンは1.1.442です。(2018/3/20現在)
	

+ tidyverseパッケージをインストールしてください。
  + `install.packages("tidyverse")`と打ち込んで実行してください。
  + RStudioのパッケージ管理ボタンから進んでもいいでしょう。
	
## Menu

### Part I RStudioの基本操作

+ RStudioの基本操作
  + 画面説明
  + Rスクリプトの実行と便利機能
	+ パッケージの読み込み
+ 外部ファイルの読み込み
  + csvファイル
  + Excel, SPSSのファイル
+ データハンドリング；自分の好きな形にデータを変形させる
	+ 列選択
	+ 行選択
	+ データの結合
	+ 値の再割り当て・新しい変数の生成
	+ データのグループ化・要約統計量
	+ 縦横変換


### Part II データの可視化

+ 可視化の重要性 
+ ggplot2パッケージによる可視化の文法
+ 実習
  + 要因計画法に即したデータの可視化
  + 一般線形モデルに即したデータの可視化
  + 一般化線形モデルに即したデータの可視化
  + 階層線形モデルに即したデータの可視化
+ Publication-readyに仕上げる方法

### 質疑応答あるいはよくある質問と答え

+ インストールの際，Core Files,32bit,64bit,Message transration，どれにチェックして入ればいいですか？
  + よくわからなければ「全て選択」かデフォルトのまま「次へ」を連打してください。
+ RとRStudioの違いは何ですか？
  + Rは統計の計算機としての機能だけを持っています(図の描画は含まれます)。もちろんそれだけで十分なのですが，ファイルの操作や図の操作，パッケージの管理などRを実際に使っているときに必要な機能を全てまとめた統合開発環境(IDE)がRStudioです。
+ RStudioのプロジェクトとは何ですか？
  + RStudioではフォルダごとに「プロジェクト」を管理することができます。プロジェクトごとに，作業領域(ワーキングディレクトリ)，履歴などを保管できるので，複数のデータ処理タスクを分けて管理できます。
+ 分散分析をする際，確実な関数はなんでしょうか？今回はaovが紹介されていました。以前，anova関数を使っていたら正しくないと先輩に言われました。
  + aov関数はRの基本パッケージに入っているものですが，タイプ I平方和で計算します。セルごとにnのサイズが違う場合，一般にタイプ III平方和を使うことが多いですが，RでタイプIII平方和を使う場合はcarパッケージや[anovakun](http://riseki.php.xdomain.jp/index.php?ANOVA君)などを導入する必要があります。
+ dplyrの言葉の由来は何ですか？
  + もともとplyr(プライヤー)というパッケージが開発され、その後効率化・高速化をした後継パッケージとしてリリースされたのがdplyr(ディープライヤー)です。dは確かデータの略だった記憶があります。
+ たくさんのcsvファイルが全てデスクトップ上にある時，結合するには一度全てのデータセットとして読み込まなくてはならないですか？（各実験参加者のx,yデータが個別のcsvファイル）
  + 一つ一つ読み込んで結合させる方法もありますが、まとめて実行したいのであれば以下のようなコードでも実現できます
  ```
  # 作業ディレクトリ(フォルダ)の下に、「csvs」というディレクトリがあって、
  # その中にたくさんのcsvファイルがあるとします
  # また、各csvファイルの変数構成は同一であるとします
  
  # csvファイル名を取得
  csv_files <- dir("csvs/")
  
  # csvファイル名をファイルパスへ
  csv_files <- paste0("csvs/", csv_files)
  
  # ファイルパスに基づき、purrr::map_dfr関数でまとめてread.csvを実行
  # この関数はまとめて実行した結果をbind_rowでどんどんまとめていきます
  data <- purrr::map_dfr(csv_files, read.csv, .id = "no")
  ```
+ 元のCSVとかの変数名って全部アルファベットじゃないといけないですよね。平仮名とか片仮名とか漢字とかの場合は全部いれなおしですよね。
  + できないわけではないですが、トラブルの原因となることがあります。dplyrパッケージには変数名を変更する関数(`rename`関数や`select`関数でちょっと工夫する)などがありますので、必要に応じて変更するといいでしょう。
+ Rでは頻繁にバージョンが新しくなりますが，こまめにアップデートした方が良いでしょうか？古いバージョンを使い続けるのは良くないでしょうか？
  + 分析者のスタンスによります。アップデートにはバグフィックスも含まれますので、私個人はこまめにアップデートを行いますが、アップデートせずにバージョンを固定していくのも分析結果の再生産性の観点から必要となることがあります。  
  大事なのは、その分析で実行しているRのバージョンやパッケージのバージョンをちゃんと意識することで、Rには`sessionInfo`という関数があります。分析レポートには、この出力結果を分析結果に付記するようにしましょう。
+ ggplot2で色でもグレースケールでもなくハッチング（編みかけ）で表現したいのですが？
  + ggplot2単独では非常に厳しいです。他の表示方法を考えたほうがいいでしょう。
+ パイプの使い方がよくわかりません
  + Rを使う上で必須ではないので、dplyrに慣れてきたら少しずつ使っていけばいいと思います。
+ ggplot2で縦軸の上限・下限を変えたいのですが・・・
  + ggplot2では，特定の範囲の**切り出し**または**拡大表示**により，表示する範囲を調整することが出来ます。前者の**切り出し**では，例えば`+ ylim(0, 10)`と追記すれば，Y軸にマッピングした変数のうち，0から10の範囲に含まれるデータのみが描画に用いられます。このとき，範囲外のデータは捨てられることに注意してください。`stat_summary()`等で要約統計量を描画していたとしたら，切り出されたデータのみで再計算が行われることで，値が変わります。後者の**拡大表示**では，例えば`coord_cartesian(ylim = c(1, 7))`と追記すると，全データは保持したまま，1から7の範囲だけが表示されます。
+ カラーパレットはどのようにして確認すれば良いですか？
  + `RColorBrewer`パッケージをロードしたあとで，`display.brewer.all()`と入力してください。
+ 水準ごとに個別に色を変更することはできますか？
  + 塗りつぶしの色を変える場合は，`scale_fill_manual(values = c("水準1" = "red", "水準2" = "blue"))`のように指定可能です。輪郭の色を変えるために`scale_colour_manual()`を使用する場合も同様です。
+ `theme_bw(base_size = 20)`などで全体のフォントサイズを変更できることは分かりましたが，X軸だけフォントサイズを変更するといったことは可能でしょうか？
  + `theme()`で詳細に設定を変更することが出来ます。X軸のフォントサイズを変更したい場合は，`+ theme(axis.text.x = element_text(size=20))`と追記してください。
+ Macなのですが，plotやggplot2で日本語文字が化けます
  + plotであれば `par(family="HiraKakuProN-W3")` の1行を実行してください(日本語のフォントファミリを指定します)
  + ggplot2であれば，`old = theme_set(theme_gray(base_family="HiraKakuProN-W3"))` の1行を実行してください(日本語のフォントファミリをテーマとして指定します)

